### ISSUE TITLE
DTK编译问题

### ISSUE THREAD

**Issue by msccreater** [rekols/developer#5]
我用的是linux mint操作系统，下载dtk源码，并且安装了相关的依赖，编译的时候还是会报错
![2017-09-11 17-39-50](https://user-images.githubusercontent.com/1811267/30268431-440264ee-9718-11e7-888e-c41ecae22d73.png)

**Comment by rekols** [comment]
QT版本不同

**Comment by msccreater** [comment]
dtk没写用的时什么Qt的版本,这个怎么查看呢?
